### ISSUE TITLE
Error with import pysaliency

### ISSUE THREAD

**Issue by junting** [matthias-k/pysaliency#1]
Hello,

I am getting an error while I am doing import pysaliency.:

Traceback (most recent call last):
  File "01-evaluate.py", line 1, in <module>
    import pysaliency
  File "/home/pysaliency-master/pysaliency/__init__.py", line 8, in <module>
    from .saliency_map_models import SaliencyMapModel, GeneralSaliencyMapModel, FixationMap
  File "/home/pysaliency-master/pysaliency/saliency_map_models.py", line 13, in <module>
    from .roc import general_roc
ImportError: No module named roc

I have followed all installation instructions.

pip install numpy scipy theano Cython natsort dill hdf5storage
pip install git+https://github.com/matthias-k/optpy
pip install git+https://github.com/matthias-k/pysaliency
python setup install

Best,

**Comment by matthias-k** [comment]
Hi,

are you using python2.7 or python3? And which operating system are you using?

Best,
  Matthias

**Comment by junting** [comment]
Hello,

I am using python 2.7. But I think I solved the problem by reinstalling it.
But now I try to evaluate my model with the 
`auc = my_model.AUC(stimuli_salicon_val[0:2], fixations_salicon_val[0:2], nonfixations='uniform',verbose=True)`

I just shows this error: 
`File "00-evaluate.py", line 64, in <module>
    auc = my_model.AUC(stimuli_salicon_val[0:2], fixations_salicon_val[0:2], nonfixations='uniform',verbose=True)
  File "/home/env/local/lib/python2.7/site-packages/pysaliency/saliency_map_models.py", line 303, in AUC
    return np.average(aucs, weights=weights)
  File "/home/env/local/lib/python2.7/site-packages/numpy/lib/function_base.py", line 933, in average
    "Axis must be specified when shapes of a and weights "
TypeError: Axis must be specified when shapes of a and weights differ.`

**Comment by matthias-k** [comment]
Hi @junting,

This looks like a bug, that might be related to the fact that right now you are only evaluating on the first two fixations (not the fixations from the first two stimuli). The `[]` operator for fixations filters on the fixations themselves to enable things like filtering by subject, position etc. Try `fixations_salicon_val[fixations_salicon_val.n < 2]`. Does this still produce the error?
The best way to filter fixations by stimulus is using `pysaliency.create_subset(stimuli, fixations, stimulus_indices)`, as filtering the stimuli might change the stimulus numbers.

**Comment by matthias-k** [comment]
I fixed the bug in https://github.com/matthias-k/pysaliency/commit/c562fd64400d450e66bdc04b4ba9b21c09d60a48.

**Comment by junting** [comment]
It works now! Thanks @matthias-k .

**Comment by fwahhab89** [comment]
I installed the pysaliency module. But I still have the original error in the issue:

File "/home/pysaliency-master/pysaliency/init.py", line 8, in 
from .saliency_map_models import SaliencyMapModel, GeneralSaliencyMapModel, FixationMap
File "/home/pysaliency-master/pysaliency/saliency_map_models.py", line 13, in 
from .roc import general_roc
ImportError: No module named roc

I am using python2.7 on a ubuntu system.
